name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
      - dev

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v2

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: site-artifact
          path: ./

      - name: Upload and Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
        with:
          artifact_name: site-artifact
          token: ${{ secrets.GITHUB_TOKEN }}
